### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Sowevo** [lhyxiaofeiyang/playFramework#1]
这个网站是怎么了,我也是从这个地方学习的play
看起来你这里的是直接爬下来的资源
好多404哈哈...

**Comment by lhyxiaofeiyang** [comment]
> 这个网站是怎么了，我也是从这个地方学习的玩
> 看起来你这里的是直接爬下来的资源
> 好多404哈哈...

这个是从公司里面找出来的html网页，网上没找到资源，只是我自己扔上来的资源，很多404我也不想...
